cmake_minimum_required(VERSION 3.21)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

project(chconv VERSION 1.3.0)

option(EMBED_MAGIC_MGC_FILE "Embed magic.mgc file database" ON)

set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/out)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/out)

# 全局设置 CMP0077 默认值为 NEW，确保FetchContent的子项目继承
set(CMAKE_POLICY_DEFAULT_CMP0077 NEW)
# 启用 CMP0135 新行为：解压文件的时间戳设为解压时的当前时间
cmake_policy(SET CMP0135 NEW)
set(FETCHCONTENT_UPDATES_DISCONNECTED ON)

if(MSVC OR CMAKE_CXX_SIMULATE_ID STREQUAL "Clang" OR CMAKE_CXX_SIMULATE_ID STREQUAL "MSVC")
    add_compile_definitions(_CRT_SECURE_NO_WARNINGS)
endif()

list(APPEND CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/cmake)

add_subdirectory(src)